version: '3.8'

services:
  # Backend API Service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: bluemed-backend
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - API_BASE_URL=https://687eade4efe65e5200875629.mockapi.io/api/v1
      - CORS_ORIGIN=http://localhost:3000
      - RATE_LIMIT_WINDOW_MS=900000
      - RATE_LIMIT_MAX_REQUESTS=100
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3001/api/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - bluemed-network
    volumes:
      - backend-logs:/app/logs

  # Frontend React Service with Vite
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: bluemed-frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    environment:
      - VITE_API_URL=http://localhost:3001/api
      - VITE_APP_NAME=BlueMed Frontend
      - VITE_APP_VERSION=1.0.0
      - VITE_ENABLE_DEBUG=false
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - bluemed-network

# Networks
networks:
  bluemed-network:
    driver: bridge
    name: bluemed-network

# Volumes
volumes:
  backend-logs:
    driver: local
    name: bluemed-backend-logs
